name: Make version

on:
  push:
    branches: [ master ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Next Version
        id: version
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.version.outputs.nextStrict }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.version.outputs.nextStrict }} > tag.txt

      - name: Archive tag
        uses: actions/upload-artifact@v3
        with:
          name: tag
          path: tag.txt

  test:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: git tag --points-at HEAD
      - run: git tag

      - name: Unarchive tag
        uses: actions/download-artifact@v3
        with:
          name: tag
      - name: Get tag
        id: tag
        run: echo "tag=$(cat tag.txt)" >> $GITHUB_OUTPUT
      - run: sed -i "s/0.0.0/${{ steps.tag.outputs.tag }}/" package.json
      - run: cat package.json
      - run: rm tag.txt
      - uses: actions/setup-node@v3
        with:
          node-version: 15.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run build
      - run: cp ./.github/.npmrc .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
