name: Build

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm test
      - run: npm run build
      - run: cp ./.github/.npmrc .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
