name: Test

on:
  pull_request:
    types:
      [ 'opened', 'synchronize' ]
    branches:
      [ 'main', 'production' ]

jobs:
  test:
    uses: ./.github/workflows/test_base.yml
    secrets: inherit
